[profile.default]
src = "src"
out = "out"
libs = ["lib"]

[etherscan]
sonic-testnet = { key = "{$SONICSCAN_API_KEY}", chain = "14601", url = "${TESTNET_API_URL}" }
sonic-mainnet = { key = "{$SONICSCAN_API_KEY}", chain = "146", url = "${SONICSCAN_API_URL}" }

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
